version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase-if-necessary
    labels:
      - 'dependencies'
    groups:
      eslint:
        patterns:
          - "*eslint*"
          - "globals"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - 'dependencies'
